FROM gemfield/deepvac:10.2-cudnn7-devel-ubuntu18.04-base
LABEL maintainer "Gemfield <gemfield@civilnet.cn>"

RUN git clone https://github.com/DeepVAC/libdeepvac libdeepvac && \
        cd libdeepvac && mkdir build && mkdir install && cd build && \
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/gemfield/libtorch;/gemfield/opencv-4.4.0/install/" -DCMAKE_INSTALL_PREFIX=/gemfield/libdeepvac/install -DBUILD_STATIC=ON .. && \
        cmake --build . --config Release && make install
